name: adme-dock
channels:
  - conda-forge
dependencies:
  - python==3.13.2
  - scikit-learn==1.6.1
  - rdkit==2020.09.1.0
  - xgboost==2.1.4
  - lightgbm==4.6.0
  - deepchem==2.8.0
  - chemprop==2.1.2
